SERVICE_ACCOUNT_FILE: "my_configuration_file_from_google_project.json"
FOLDER_ID: "ID_DA_PASTA_PRINCIPAL"


SUBFOLDERS:
  Espiritismo e Religião: "ID_DA_PASTA_ESPIRITISMO"
  Autoajuda e Espiritualidade: "ID_DA_PASTA_AUTOAJUDA"
  Magia e Ocultismo: "ID_DA_PASTA_MAGIA"
  Filosofia e Conhecimento: "ID_DA_PASTA_FILOSOFIA"
  Autores Populares: "ID_DA_PASTA_AUTORES"
  Outros: "ID_DA_PASTA_OUTROS"

PASTA_DUPLICADOS: "ID_DA_PASTA_DUPLICADOS"

KEYWORDS:
  Espiritismo e Religião: ["espiritismo", "kardec", "mediunidade", "deus", "chico", "xavier", 
        "divaldo", "franco", "herculano", "pires", "allan"]
  Autoajuda e Espiritualidade: ["vida", "amor", "luz", "ser", "você", "mente", "caminho", "sabedoria",
        "autoajuda", "poder", "mente", "energia", "positiva"]
  Magia e Ocultismo: ["magia", "cabala", "umbanda", "bruxa", "tarô", "segredos", "ocultismo",
        "astrologia", "alquimia", "hermetismo", "misticismo", "esoterismo",
        "aleister", "crowley", "eliphas", "levi", "piobb", "paracelso", "grimório",
        "thoth", "goetia", "thelema", "hermética", "oculto"]
  Filosofia e Conhecimento: ["curso", "filosofia", "manual", "sabedoria", "pensamento", "história",
        "conhecimento", "ciência", "racionalismo", "sociologia", "teoria"]
  Autores Populares: ["xavier", "divaldo", "augusto", "richard", "daniel", "gary", "lucia",
        "helena", "joseph", "allan", "michael", "robert", "david", "ernesto",
        "paulo", "ana", "monica", "robson", "rubens"]

PALAVRAS_IGNORADAS:
    ["a", "o", "as", "os", "um", "uma", "uns", "umas", 
    "de", "do", "da", "dos", "das", "e", "em", "para", 
    "por", "com", "sem", "sobre", "entre", "seu", "sua", 
    "seus", "suas", "que", "na", "no", "nas", "nos"]